apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Google Kubernetes Engine (GKE) specific configuration

resources:
  - ingress.yaml
  - storageclass.yaml
  - backendconfig.yaml

commonLabels:
  cloud.provider: gcp
